#!/bin/bash
set -e  # Exit on error

# Function to print a message with a separator
print_message() {
    echo -e "\n=== $1 ==="
}

# Update system dependencies
print_message "Updating dependencies"
sudo apt update
sudo apt upgrade -y
sudo apt install -y git curl zsh

# Set Zsh as the default shell
print_message "Setting Zsh as default shell"
chsh -s "$(which zsh)"

# Install Oh My Zsh
print_message "Installing Oh My Zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install Kitty terminal
print_message "Installing Kitty terminal"
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

# Set up Kitty
print_message "Setting up Kitty"
KITTY_PATH="$HOME/.local/kitty.app"
mkdir -p "$HOME/.local/bin"
ln -sf "$KITTY_PATH/bin/kitty" "$KITTY_PATH/bin/kitten" "$HOME/.local/bin/"
mkdir -p "$HOME/.local/share/applications"
cp "$KITTY_PATH/share/applications/kitty.desktop" "$HOME/.local/share/applications/"
cp "$KITTY_PATH/share/applications/kitty-open.desktop" "$HOME/.local/share/applications/"

# Update Kitty desktop file paths
sed -i "s|Icon=kitty|Icon=$KITTY_PATH/share/icons/hicolor/256x256/apps/kitty.png|g" "$HOME/.local/share/applications/kitty*.desktop"
sed -i "s|Exec=kitty|Exec=$KITTY_PATH/bin/kitty|g" "$HOME/.local/share/applications/kitty*.desktop"

# Set Kitty as the default terminal
echo 'kitty.desktop' > "$HOME/.config/xdg-terminals.list"

# Create Kitty configuration
print_message "Creating Kitty configuration"
mkdir -p "$HOME/.config/kitty/sessions"

cat > "$HOME/.config/kitty/kitty.conf" << EOF
# Terminal settings
startup_session ~/.config/kitty/sessions/startup.conf
remember_window_size no
initial_window_width 1366
initial_window_height 768
hide_window_decorations yes

# Font settings
font_family FiraCodeNerdFont
italic_font auto
bold_italic_font auto
font_size 10

# URL handling
detect_urls yes
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
open_url_with default
url_style curly

# Cursor settings
cursor #8fee96
copy_on_select yes
cursor_shape underline
cursor_underline_thickness 2.0

# Terminal emulation
term xterm-256color

# Background opacity
background_opacity 0.4

# Theme
include current-theme.conf
EOF

# Create Kitty startup session
cat > "$HOME/.config/kitty/sessions/startup.conf" << EOF
os_window_state maximized
EOF

# Create Kitty theme
cat > "$HOME/.config/kitty/current-theme.conf" << EOF
# This file is auto-generated by shipwright.nvim
# vim:ft=kitty
## name: duckbones
## author: Michael Chris Lopez
## license: MIT
## upstream: https://github.com/mcchrish/zenbones.nvim/raw/main/extras/kitty/duckbones.conf
## blurb: A zenbones variant inspired by Spaceduck.
foreground                      #EBEFC0
background                      #0E101A
selection_foreground            #EBEFC0
selection_background            #37382D
cursor                          #EDF2C2
cursor_text_color               #0E101A
active_tab_foreground           #EBEFC0
active_tab_background           #4D3191
inactive_tab_foreground         #EBEFC0
inactive_tab_background         #232738
color0 #0E101A
color8 #2B2F46
color1 #E03600
color9 #FF4821
color2  #5DCD97
color10 #58DB9E
color3  #E39500
color11 #F6A100
color4  #00A3CB
color12 #00B4E0
color5  #795CCC
color13 #B3A1E6
color6  #00A3CB
color14 #00B4E0
color7  #EBEFC0
color15 #B3B692
EOF

# Clone Kitty themes
print_message "Cloning Kitty themes"
git clone https://github.com/dexpota/kitty-themes.git "$HOME/.config/kitty/kitty-themes"

# Create .zshrc file
print_message "Creating .zshrc file"
cat > "$HOME/.zshrc" << EOF
# Enable Powerlevel10k instant prompt
if [[ -r "\${XDG_CACHE_HOME:-\$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh" ]]; then
  source "\${XDG_CACHE_HOME:-\$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh"
fi

# Oh My Zsh configuration
export ZSH="\$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git zsh-syntax-highlighting zsh-autosuggestions)
source \$ZSH/oh-my-zsh.sh

# Aliases
alias makef="make fclean"
alias format="python3 -m c_formatter_42"
alias xclean="/bin/bash \$HOME/xclean.sh"
alias commit="git commit -m"
alias add="git add ."
alias push="git push"
alias status="git status"
alias checkout="git checkout"
alias lock="ft_lock"
alias nvim="~/squashfs-root/usr/bin/nvim"

# Powerlevel10k configuration
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme
EOF

# Install Zsh utilities
print_message "Installing Zsh utilities"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting"
git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
git clone https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k"

print_message "Script completed successfully"